# Generated by Django 4.2.30 on 2026-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
